inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-rails

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Max: 32
